/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CTK5oqBBWGd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Card } from "@/components/ui/card"
import { JSX, SVGProps } from "react"

export function ChatInterface() {
  return (
    <div className="flex flex-col items-center justify-between min-h-screen bg-[#1e1e1e] text-white">
      <header className="flex items-center justify-between w-full p-4">
        <h1 className="text-lg font-semibold">ChatGPT 4.0</h1>
        <Avatar>
          <AvatarImage src="/placeholder-user.jpg" />
          <AvatarFallback>S</AvatarFallback>
        </Avatar>
      </header>
      <main className="flex flex-col items-center justify-center flex-1">
        <DoorOpenIcon className="w-12 h-12 mb-4" />
        <div className="grid grid-cols-2 gap-6 md:grid-cols-4">
          <Card className="flex flex-col items-center justify-center p-2 bg-[#2c2c2c] rounded-lg w-36">
            <FeatherIcon className="w-4 h-4 mb-1 text-purple-500" />
            <p className="text-xs text-gray-300">Text inviting friend to wedding</p>
          </Card>
          <Card className="flex flex-col items-center justify-center p-2 bg-[#2c2c2c] rounded-lg w-36">
            <CalendarDaysIcon className="w-4 h-4 mb-1 text-yellow-500" />
            <p className="text-xs text-gray-300">Plan a relaxing day</p>
          </Card>
          <Card className="flex flex-col items-center justify-center p-2 bg-[#2c2c2c] rounded-lg w-36">
            <LightbulbIcon className="w-4 h-4 mb-1 text-yellow-500" />
            <p className="text-xs text-gray-300">Activities to make friends in new city</p>
          </Card>
          <Card className="flex flex-col items-center justify-center p-2 bg-[#2c2c2c] rounded-lg w-36">
            <GraduationCapIcon className="w-4 h-4 mb-1 text-blue-500" />
            <p className="text-xs text-gray-300">Quiz me on world capitals</p>
          </Card>
        </div>
      </main>
      <footer className="w-full p-4">
        <div className="relative flex items-center w-full max-w-2xl mx-auto bg-[#2c2c2c] rounded-full">
          <ActivityIcon className="absolute left-4 w-5 h-5 text-gray-400" />
          <input
            type="text"
            placeholder="Message ChatGPT"
            className="w-full px-12 py-2 text-sm bg-transparent border-none outline-none"
          />
          <SendIcon className="absolute right-4 w-5 h-5 text-gray-400" />
        </div>
        <p className="mt-2 text-xs text-center text-gray-500">ChatGPT can make mistakes. Check important info.</p>
      </footer>
    </div>
  )
}

function ActivityIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2" />
    </svg>
  )
}


function CalendarDaysIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  )
}


function DoorOpenIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M13 4h3a2 2 0 0 1 2 2v14" />
      <path d="M2 20h3" />
      <path d="M13 20h9" />
      <path d="M10 12v.01" />
      <path d="M13 4.562v16.157a1 1 0 0 1-1.242.97L5 20V5.562a2 2 0 0 1 1.515-1.94l4-1A2 2 0 0 1 13 4.561Z" />
    </svg>
  )
}


function FeatherIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.67 19a2 2 0 0 0 1.416-.588l6.154-6.172a6 6 0 0 0-8.49-8.49L5.586 9.914A2 2 0 0 0 5 11.328V18a1 1 0 0 0 1 1z" />
      <path d="M16 8 2 22" />
      <path d="M17.5 15H9" />
    </svg>
  )
}


function GraduationCapIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z" />
      <path d="M22 10v6" />
      <path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5" />
    </svg>
  )
}


function LightbulbIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5" />
      <path d="M9 18h6" />
      <path d="M10 22h4" />
    </svg>
  )
}


function SendIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}


function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
